[package]
name = "nucleo-unstable"
description = "plug and play high performance fuzzy matcher"
authors = ["Pascal Kuthe <pascalkuthe@pm.me>"]
version = "0.0.1-alpha.1"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/alexrutar/nucleo-unstable"
readme = "README.md"
exclude = ["/typos.toml", "/tarpaulin.toml"]

[lib]

[dependencies]
nucleo-matcher = { version = "0.0.1-alpha.1", path = "matcher", package = "nucleo-matcher-unstable" }
parking_lot = { version = "0.12.1", features = ["send_guard", "arc_lock"] }
rayon = "1.7.0"

[workspace]
members = ["matcher"]
